"""
SQLAlchemy ORM models for the Trading System.

All models inherit from the shared DeclarativeBase and use proper
column types, indexes, and default timestamps in IST.
"""

from datetime import datetime, timezone, timedelta

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSON

from app.infrastructure.database.session import Base

# IST offset
IST = timezone(timedelta(hours=5, minutes=30))


def _now_ist() -> datetime:
    """Return the current datetime in IST."""
    return datetime.now(IST)


class Trade(Base):
    """Completed or in-progress trade records."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    market = Column(String(30), nullable=False, default="indian_equity")
    direction = Column(String(10), nullable=False)  # long / short
    strategy = Column(String(50), nullable=False, index=True)

    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    quantity = Column(Integer, nullable=False, default=1)

    entry_time = Column(DateTime(timezone=True), nullable=False, default=_now_ist)
    exit_time = Column(DateTime(timezone=True), nullable=True)

    pnl = Column(Float, nullable=True, default=0.0)
    charges = Column(Float, nullable=True, default=0.0)
    net_pnl = Column(Float, nullable=True, default=0.0)
    score = Column(Float, nullable=True)

    status = Column(String(20), nullable=False, default="open", index=True)
    notes = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), default=_now_ist)
    updated_at = Column(DateTime(timezone=True), default=_now_ist, onupdate=_now_ist)

    __table_args__ = (
        Index("ix_trades_symbol_status", "symbol", "status"),
        Index("ix_trades_entry_time", "entry_time"),
    )

    def __repr__(self) -> str:
        return f"<Trade {self.id} {self.symbol} {self.direction} {self.status}>"


class Signal(Base):
    """Trading signals generated by strategies and ML models."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    market = Column(String(30), nullable=False, default="indian_equity")
    direction = Column(String(10), nullable=False)
    strategy = Column(String(50), nullable=False, index=True)

    # Composite score & breakdown
    score = Column(Float, nullable=False)
    technical_score = Column(Float, nullable=True, default=0.0)
    sentiment_score = Column(Float, nullable=True, default=0.0)
    volume_score = Column(Float, nullable=True, default=0.0)
    regime_score = Column(Float, nullable=True, default=0.0)
    macro_score = Column(Float, nullable=True, default=0.0)

    # Price targets
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)

    status = Column(String(20), nullable=False, default="active", index=True)
    created_at = Column(DateTime(timezone=True), default=_now_ist)
    expires_at = Column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index("ix_signals_status_created", "status", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Signal {self.id} {self.symbol} {self.direction} score={self.score}>"


class Position(Base):
    """Currently open positions."""

    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    market = Column(String(30), nullable=False, default="indian_equity")
    direction = Column(String(10), nullable=False)

    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=True)
    quantity = Column(Integer, nullable=False, default=1)
    unrealized_pnl = Column(Float, nullable=True, default=0.0)

    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    strategy = Column(String(50), nullable=True)

    opened_at = Column(DateTime(timezone=True), default=_now_ist)
    updated_at = Column(DateTime(timezone=True), default=_now_ist, onupdate=_now_ist)

    __table_args__ = (
        Index("ix_positions_symbol_market", "symbol", "market"),
    )

    def __repr__(self) -> str:
        return f"<Position {self.id} {self.symbol} qty={self.quantity}>"


class PortfolioSnapshot(Base):
    """Daily portfolio snapshots for tracking capital and performance."""

    __tablename__ = "portfolio_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, unique=True, index=True)

    total_capital = Column(Float, nullable=False)
    used_capital = Column(Float, nullable=False, default=0.0)
    cash = Column(Float, nullable=False)

    daily_pnl = Column(Float, nullable=False, default=0.0)
    cumulative_pnl = Column(Float, nullable=False, default=0.0)
    drawdown = Column(Float, nullable=False, default=0.0)
    max_drawdown = Column(Float, nullable=False, default=0.0)

    created_at = Column(DateTime(timezone=True), default=_now_ist)

    def __repr__(self) -> str:
        return f"<PortfolioSnapshot {self.date} cap={self.total_capital}>"


class MarketRegimeLog(Base):
    """Logged market regime detections with confidence and indicators."""

    __tablename__ = "market_regime_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, default=_now_ist, index=True)
    regime = Column(String(30), nullable=False)
    confidence = Column(Float, nullable=False)
    indicators_json = Column(JSON, nullable=True)

    def __repr__(self) -> str:
        return f"<MarketRegime {self.regime} conf={self.confidence}>"


class BacktestResult(Base):
    """Persisted backtest results for strategy evaluation."""

    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    strategy = Column(String(50), nullable=False, index=True)

    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)

    total_return = Column(Float, nullable=True)
    cagr = Column(Float, nullable=True)
    sharpe = Column(Float, nullable=True)
    sortino = Column(Float, nullable=True)
    max_drawdown = Column(Float, nullable=True)
    win_rate = Column(Float, nullable=True)
    profit_factor = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=True)

    result_json = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), default=_now_ist)

    def __repr__(self) -> str:
        return f"<BacktestResult {self.strategy} on {self.symbol}>"


class DailyPnL(Base):
    """Aggregated daily profit & loss records."""

    __tablename__ = "daily_pnl"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, unique=True, index=True)

    pnl = Column(Float, nullable=False, default=0.0)
    trades_count = Column(Integer, nullable=False, default=0)
    wins = Column(Integer, nullable=False, default=0)
    losses = Column(Integer, nullable=False, default=0)

    created_at = Column(DateTime(timezone=True), default=_now_ist)

    def __repr__(self) -> str:
        return f"<DailyPnL {self.date} pnl={self.pnl}>"
